# Generated by Django 3.0.4 on 2020-03-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Disc', models.TextField()),
                ('Price', models.IntegerField()),
                ('Img', models.ImageField(upload_to='pics')),
                ('Offer', models.BooleanField(default=False)),
            ],
        ),
    ]
